name: 02 workflow events

on:
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *' # Runs every day at midnight 0 0 * * *' only 5 digits are allowed
  workflow_dispatch:     # Manually trigger the workflow from the GitHub UI  

jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Workflow is running successfully 🚀a(n) ${{ github.event_name }} event."
